### ISSUE TITLE
Rename respondWith()/canRespond → transitionWhile()/canTransition

### ISSUE THREAD

**Issue by fabiancook** [frehner/appHistory#2]
Looking at the spec, they have changed from the fetch like `respondWith`, to AppHistory independent `transitionWhile` 

https://github.com/WICG/app-history/issues/94#issuecomment-888248569
https://github.com/WICG/app-history/pull/151

In the tests and code for this repo, `respondWith` is used

**Comment by fabiancook** [comment]
This also changes `canRespond` to `canTransition` 

https://github.com/Yannic/chromium/commit/6cf2470054220f5bd919de04399f0e31e6b3f783#diff-e6da4f6c72af2c3585fe2b7c17f04ee183773bd20a7dd5171a949f3f90e4d3a9R14

**Comment by frehner** [comment]
I haven’t had time to work on this repo for awhile. 😔

**Comment by fabiancook** [comment]
No worries at all! I am about to raise a PR, a direct replace + yarn test pass!

**Comment by frehner** [comment]
Fix in #3 I believe.

**Comment by ar2r13** [comment]
@frehner Can you publish changes on npm?
