### ISSUE TITLE
Proposal was renamed to Navigation.api

### ISSUE THREAD

**Issue by eshimischi** [frehner/appHistory#4]
Hi, thanks for your polyfill, but proposal changed their name some days ago [navigation-api](https://github.com/WICG/navigation-api)

**Comment by frehner** [comment]
Yeah, that's exciting! There's also been lots of movement/changes recently, which is also great.

I currently don't have the time to put into updating / maintaining this polyfill. :(

**Comment by eshimischi** [comment]
It's okay, take your time!
